# pgadmin 4
pgadmin:
    # login : pgadmin4@pgadmin.org - password : admin
    image: fenglc/pgadmin4:2.1-python2.7-alpine
    container_name: pgadmin4_workshop
    links:
      - postgres:postgres
    ports:
      - 5050:5050
# database
postgres:
  image: postgres:latest
  container_name: postgres_workshop
  environment:
    - "TZ=Europe/Paris"
    - "POSTGRES_USER=docker"
    - "POSTGRES_PASSWORD=docker"
    - "POSTGRES_DB=workshop"
  ports:
    - "5432:5432"  # credentials (docker:docker)
  volumes:
    - "./initdb:/docker-entrypoint-initdb.d"